# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='police_report',
            field=models.CharField(choices=[('dont_report', 'Do not Report'), ('text', 'Report by Text'), ('call', 'Report by Call')], default='dont_report', max_length=10),
        ),
    ]
